import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import Header from './components/header'

const roboto = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Swaps Viewer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
